import Link from "next/link";

export default function PrivacyPage() {
  return (
    <div style={{ minHeight: "100dvh", background: "#f8f9fa" }}>
      <header style={{ height: 56, display: "flex", alignItems: "center", padding: "0 clamp(16px, 3vw, 32px)", background: "#fff", borderBottom: "1px solid #e5e7eb", position: "sticky", top: 0, zIndex: 40 }}>
        <Link href="/" style={{ fontSize: 18, fontWeight: 800, letterSpacing: "-0.04em", color: "#0f172a" }}>Lawyered</Link>
      </header>

      <main style={{ maxWidth: 720, margin: "0 auto", padding: "40px clamp(16px, 4vw, 32px) 80px" }}>
        <h1 style={{ fontSize: 28, marginBottom: 8 }}>Privacy Policy</h1>
        <p style={{ fontSize: 13, color: "#94a3b8", marginBottom: 32 }}>Last updated: April 2025</p>

        <div style={{ display: "flex", flexDirection: "column", gap: 24, fontSize: 14, color: "#475569", lineHeight: 1.8 }}>
          <section>
            <h2 style={{ fontSize: 18, color: "#0f172a", marginBottom: 8 }}>What We Collect</h2>
            <p>When you use Lawyered, we collect:</p>
            <ul style={{ paddingLeft: 20, marginTop: 8 }}>
              <li>Your Google account information (name, email, profile photo) for authentication</li>
              <li>Legal queries and case research you submit</li>
              <li>Case analysis results generated by the system</li>
            </ul>
          </section>

          <section>
            <h2 style={{ fontSize: 18, color: "#0f172a", marginBottom: 8 }}>How We Use Your Data</h2>
            <ul style={{ paddingLeft: 20 }}>
              <li>To provide legal research and analysis services</li>
              <li>To save your research history so you can revisit it</li>
              <li>To improve the quality of our AI analysis</li>
            </ul>
          </section>

          <section>
            <h2 style={{ fontSize: 18, color: "#0f172a", marginBottom: 8 }}>Third-Party Services</h2>
            <p>Lawyered uses the following third-party services:</p>
            <ul style={{ paddingLeft: 20, marginTop: 8 }}>
              <li><strong>Google Firebase</strong> — Authentication, database storage (Firestore)</li>
              <li><strong>Google Cloud / Gemini AI</strong> — AI-powered legal analysis</li>
              <li><strong>CourtListener (Free Law Project)</strong> — Public court case database (no user data shared)</li>
            </ul>
            <p style={{ marginTop: 8 }}>We do not sell or share your personal data with any other third parties.</p>
          </section>

          <section>
            <h2 style={{ fontSize: 18, color: "#0f172a", marginBottom: 8 }}>Data Security</h2>
            <p>Your data is stored in Google Cloud Firestore with security rules that restrict access to your own documents. API keys are stored as environment variables and never exposed to the client.</p>
          </section>

          <section>
            <h2 style={{ fontSize: 18, color: "#0f172a", marginBottom: 8 }}>Attorney-Client Privilege</h2>
            <p>Lawyered is an AI-powered legal information tool, <strong>not a law firm</strong>. Using Lawyered does not create an attorney-client relationship. Information provided is legal information based on public court records, not legal advice. Your queries are processed in a secure environment, but are not protected by attorney-client privilege.</p>
          </section>

          <section>
            <h2 style={{ fontSize: 18, color: "#0f172a", marginBottom: 8 }}>Your Rights</h2>
            <p>You can delete your research history at any time from the History page. To request complete account deletion, contact us.</p>
          </section>

          <section>
            <h2 style={{ fontSize: 18, color: "#0f172a", marginBottom: 8 }}>Not Legal Advice</h2>
            <p>All information provided by Lawyered is for informational purposes only and does not constitute legal advice. Always consult a licensed attorney for advice specific to your situation.</p>
          </section>
        </div>
      </main>
    </div>
  );
}
